version: '3'

services:
  db:
    env_file: database.conf
    image: postgres:latest
#    ports:
#      - "5432:5432"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: ./web
    depends_on:
      - db
    environment:
      STAGE: test
    env_file: database.conf
    ports:
      - "80:5000"
    volumes:
      - ./app:/usr/src/app
    restart: always

